project_backlog/backlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('dashboard.urls')),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
]

project_backlog/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index_dashboard'),
]

project_backlog/projects/urls.py
from django.urls import path, include

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='index_projects'),
    path('add/', views.add_project, name='add_project'),
    path('edit/<uuid:project_id>', views.edit_project, name='edit_project'),
    path('delete/<uuid:project_id>', views.delete_project, name='delete_project'),
]

project_backlog/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('<uuid:project_id>', views.index_tasks, name='index_tasks'),
    path('add/<uuid:project_id>', views.add_task, name='add_task'),
    path('edit/<uuid:task_id>', views.edit_task, name='edit_task'),
    path('delete/<uuid:task_id>', views.delete_task, name='delete_task'),
]

project_backlog/projects/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Projects(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='projects')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'projects'

project_backlog/projects/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Projects

class ProjectForm(ModelForm):
    created_by = forms.ModelChoiceField(
        queryset=User.objects.all(),
        widget=forms.Select(attrs={'class': 'form-select'}),
        required=False,
        label='Select User :',
    )
    class Meta:
        model = Projects
        fields = ['name', 'description', 'created_by']
        labels = {
            'name': 'Name :',
            'description': 'Description :',
            'created_by': 'Select User :',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control' , 'style':'height: 100px'}),
            'description': forms.Textarea(attrs={'class': 'form-control' , 'style':'height: 100px'}),
        }

project_backlog/projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Projects
from .forms import ProjectForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    all_projects = Projects.objects.all()
    
    filter_all_projects = all_projects

    # Filter berdasarkan project
    project_filter = request.GET.get('filter_project', '')
    if project_filter:
        filter_all_projects = filter_all_projects.filter(id=project_filter)

    # Filter berdasarkan created_by
    created_filter = request.GET.get('filter_created_by', '')
    if created_filter:
        filter_all_projects = filter_all_projects.filter(created_by__id=created_filter)

    # Mengirim daftar user untuk dropdown filter
    users = User.objects.all()

    context = {
        'all_projects': all_projects,
        'projects': filter_all_projects,
        'users': users,
        'current_project': project_filter,
        'current_created': created_filter,
    }
    return render(request, 'projects/index.html', context)

@login_required
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.save()
            return redirect('projects:index_projects')
    else:
        form = ProjectForm()
    return render(request, 'projects/form_project.html', {'form': form})

@login_required
def edit_project(request, project_id):
    project = get_object_or_404(Projects, id=project_id)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('projects:index_projects')
    else:
        form = ProjectForm(instance=project)
    return render(request, 'projects/form_project.html', {'form': form})

@login_required
def delete_project(request, project_id):
    project = get_object_or_404(Projects, id=project_id)
    project.delete()
    return redirect('projects:index_projects')

project_backlog/projects/templates/projects/form_project.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid mt-2">
    <div class="d-flex justify-content-between mb-4">
        <h1>
            <i class="bi bi-folder2-open me-2"></i>
            Project Form
        </h1>
        <nav aria-label="breadcrumb" class="align-self-end">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url "dashboard:index_dashboard" %}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{% url "projects:index_projects" %}">Projects</a></li>
                <li class="breadcrumb-item active" aria-current="page">Project Form</li>
            </ol>
        </nav>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">{{form.name.label}}<span class="text-danger ms-2">*</span></label>
            {{form.name}}
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">{{form.description.label}}<span class="text-danger ms-2">*</span></label>
            {{form.description}}
        </div>
        <div class="mb-3">
            <label for="id_created_by" class="form-label">{{form.created_by.label}}</label>
            {{form.created_by}}
        </div>
        <button type="submit" class="btn btn-sm btn-primary">Save</button>
        <a href="{% url "projects:index_projects" %}" class="btn btn-sm btn-secondary">Cancel</a>
    </form>
</div>
{% endblock content %}

project_backlog/projects/templates/projects/index.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
    <div class="d-flex justify-content-between mb-4">
        <h1>
            <i class="fa-solid fa-folder-open me-2"></i>
            Projects
        </h1>
        <nav aria-label="breadcrumb" class="align-self-end">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url "dashboard:index_dashboard" %}" class="link-underline link-underline-opacity-0">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Projects</li>
            </ol>
        </nav>
    </div>

    <!-- Tabel Tasks -->
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <div class="card-title m-0 fw-semibold">
                <i class="fa-solid fa-table me-2"></i>
                Table
            </div>
            <a href="{% url "projects:add_project" %}" class="btn btn-sm btn-primary">
                <i class="fa-solid fa-plus me-1"></i>
                Add Project
            </a>
        </div>
        <div class="card-body">
            <!-- Form Filter -->
            <form method="GET" class="row mb-4">
                <div class="col">
                    <label for="filter_project" class="mb-2">Filter Project:</label>
                    <select class="form-select form-select-sm" name="filter_project" id="filter_project" onchange="this.form.submit()">
                        <option value="">All</option>
                        {% for all_project in all_projects %}
                            <option value="{{all_project.id}}" {% if current_project == all_project.id|stringformat:"s" %}selected{% endif %}>
                                {{all_project.name}}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col">
                    <label for="filter_created_by" class="mb-2">Filter Created_by:</label>
                    <select class="form-select form-select-sm" name="filter_created_by" id="filter_created_by" onchange="this.form.submit()">
                        <option value="">All</option>
                        {% for user in users %}
                            <option value="{{ user.id }}" {% if current_created == user.id|stringformat:"s" %}selected{% endif %}>
                                {{ user.username }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-auto align-self-end">
                    <a href="{% url 'projects:index_projects' %}" class="btn btn-sm btn-secondary">
                        <i class="fa-solid fa-rotate me-1"></i>
                        Reset
                    </a>
                </div>
            </form>
            <table class="table table-striped table-hover table-bordered">
                <thead class="text-center">
                    <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Project</th>
                        <th scope="col">Description</th>
                        <th scope="col">Created_by</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for project in projects %}
                        <tr>
                            <th class="text-center">{{ forloop.counter }}</th>
                            <td class="text-center"><a href="{% url "tasks:index_tasks" project.id %}" class="link-underline link-underline-opacity-0">{{ project.name }}</a></td>
                            <td class="text-break">{{ project.description }}</td>
                            <td class="text-center">{{ project.created_by }}</td>
                            <td class="text-center col-1">
                                <a href="{% url "projects:edit_project" project.id %}" class="btn btn-sm btn-warning" title="Edit">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a>
                                <a href="{% url "projects:delete_project" project.id %}" class="btn btn-sm btn-danger" title="Delete">
                                    <i class="fa-solid fa-trash-can"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}